// Bumps the Gradle daemon's JVM heap/metaspace for Android builds.
//
// Why this exists: a release build (yarn build:android:prod:apk) was
// failing during `:*:lintVitalAnalyzeRelease` for several native modules
// with an out-of-memory "Metaspace" error. The default gradle.properties
// generated by `expo prebuild` only allocates -Xmx2048m / MaxMetaspaceSize
// 512m, which isn't enough headroom once lint runs on top of the JS bundle
// + all native module compilation in the same daemon. Hand-editing
// android/gradle.properties directly doesn't stick — that file is
// regenerated from scratch on every `expo prebuild`/`expo prebuild
// --clean` — so this is a config plugin instead, applied automatically on
// every prebuild.
const { withGradleProperties } = require('@expo/config-plugins');

const JVM_ARGS_KEY = 'org.gradle.jvmargs';
const JVM_ARGS_VALUE = '-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError';

const withAndroidGradleJvmArgs = (config) =>
  withGradleProperties(config, (config) => {
    const existing = config.modResults.find(
      (item) => item.type === 'property' && item.key === JVM_ARGS_KEY,
    );
    if (existing) {
      existing.value = JVM_ARGS_VALUE;
    } else {
      config.modResults.push({ type: 'property', key: JVM_ARGS_KEY, value: JVM_ARGS_VALUE });
    }
    return config;
  });

module.exports = withAndroidGradleJvmArgs;
